### ISSUE TITLE
How can we ensure the simple calculator program gracefully handles division by zero, preventing crashes or erroneous outputs?

### ISSUE THREAD

**Issue by adr9x9** [adr9x9/Assembly#6]

**Comment by RakibulMRH** [comment]
To prevent division by zero mishaps, we can implement a robust error-checking mechanism that detects when the user attempts to divide by zero. Upon such an attempt, the program could display a friendly message informing the user of their mathematical faux pas and gracefully handle the situation by offering them a chance to correct their arithmetic oversight.
